#!/bin/bash

#arr=("horse/" "nqueens/" "maze/")
arr=("maze/")

table()
{
    for j in $1*.h
    do
        #echo $fparams $pparams
        cfile="${j%.h}"
        cfun="${cfile#*\/}"
        sed "s~\".*\"~\"$j\"~" ./executor.cpp -i
        sed "s~<< .* <<~<< $cfun$fparams <<~" ./executor.cpp -i
        g++ -std=c++2a executor.cpp -o $i$cfun 
        lastval=$(awk -v var=$cfun '($1 == var) {print $2}' data/$ctest.dat) 
        newstdin=$(./$i$cfun $pparams)
        echo $cfun
        echo -e "$newstdin" | head -n -1
        echo
        newval=$(echo -e "$newstdin" | tail -n1)
        #if [[ $(echo -e "$newval" | wc -w) -eq 1 ]]
        #then
        sed "s~$cfun\t.*~$cfun\t$(echo $lastval + $newval | bc)~" data/$ctest.dat -i
        #else
        #    sed "s~$cfun\t.*~$cfun\t$((lastval + 100000000000))~" $ctest.dat -i
        #fi
    done
}

for i in ${arr[@]}
do
    ctest=${i%/}
    > data/$ctest.dat
    for it in $i*.h
    do  
        cfile="${it%.h}"
        cfun="${cfile#*\/}"
        echo -e "$cfun\t0" >> data/$ctest.dat
    done


    if [[ $i != "maze/" ]]
    then
        for newit in {1..3}
        do
            echo "${ctest^^} $newit --------------------------------------------------------------"

                printf "Ingrese n: "
                read n
                printf "Ingrese x: "
                read x 
                printf "Ingrese y: "
                read y
                echo
                fparams="(n, x, y)"
                pparams="$n $x $y"
                table $i
        done
    else
        #for maz in maze/*.txt
        #do
        #    echo "${maz^^}  ----------------------------------------------------------------------"
            fparams="()"
            pparams="a"
            table $i
        #done
    fi


    echo "Tabla de resultados: ========================================================="
    sort -k2g data/$ctest.dat
    echo -e "==============================================================================\n\n"

    gnuplot -e "set boxwidth 2; set style fill solid 1.00 border 0;
        plot 'data/$ctest.dat' using 2: xtic(1) with histogram;
        " -persist
done
